---
title: "Exp 3: Model simulations"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage{array}
 \usepackage{multirow}
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}
---

# Setup

```{r , include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', 
                      echo=TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
library(ggplot2)
library(readr)
library(boot)

th <- theme_classic()
theme_set(th)
```

load data (subject, exp, scenes)


## Localization Error - Adaptive computation

```{r echo=FALSE, results='hide'}

# covariates pre-processed by `scripts/exp1_attention_process_chains.R`
exp_data <- read_csv("../data/exp3/exp3_localization_error_adaptive_computation_td_att.csv") %>%
  filter(frame > 24)

dnd_data <- read_csv("../data/exp3/exp3_localization_error_adaptive_computation_td_dnd.csv") %>%
# filter(frame == max(frame)) %>%
  select(-contains("pred"))

model_perf <- read_csv("../data/exp3/exp3_localization_error_adaptive_computation_td_perf.csv")

mean(model_perf$td_acc)

acc_thresh = 0.99
loc_error_thresh = 3.0
ecc_thresh = 0.90
exp_data <- exp_data %>%
  mutate(sensitivity = pmax(sensitivity, -100)) %>%
  left_join(model_perf, by = c("chain", "scene", "tracker")) %>%
# remove targets that were not correctly tracked
  # filter(td_acc > acc_thresh) %>%
  left_join(dnd_data, by = c("chain", "scene", "frame", "tracker")) %>%
  group_by(scene, frame, tracker) %>%
  summarise(across(c(cycles, pred_x, pred_y, loc_error, nn_dist, td_acc, sensitivity),
                   list(mean = mean)),
            )%>%
  ungroup() %>%
  filter(td_acc_mean > acc_thresh) %>%
  # remove extreme loc error
  mutate(z_loc_error = scale(loc_error_mean)) %>%
  filter(z_loc_error < loc_error_thresh) %>%
  mutate(deg_loc_error = (loc_error_mean / 800) * 6.97,
         deg_nn_dist = (nn_dist_mean / 800) * 6.97,
         ecc = sqrt(pred_x_mean^2 + pred_y_mean^2) / 400) %>%
  filter(ecc < ecc_thresh)

# used in fixed resource model
avg_cycles = mean(exp_data$cycles_mean)
```

## Localization Error - Adaptive computation


```{r}

exp_data %>%
  ggplot(aes(x = cycles_mean)) + 
  geom_histogram(bins=100)


loc_error <- exp_data %>%
  select(scene, frame, tracker, nn_dist_mean, deg_nn_dist, deg_loc_error, 
         loc_error_mean, cycles_mean, 
         sensitivity_mean)

loc_error %>%
  ggplot(aes(x = deg_nn_dist)) + 
  geom_histogram(bins=30)

exp_data %>%
  ggplot(aes(x = loc_error_mean)) + 
  geom_histogram(bins=100)

```

```{r}

# bins from panel B (visually estimated)
panel_bins = c(1.0, 1.4, 1.7, 2.1, 2.6, 3.6)
# breaks = c(.32, 1.2, 1.55, 1.9, 2.35, 3.1, 4.0)
breaks = c(.8, 1.2, 1.55, 1.9, 2.35, 3.1, 4.0)
# breaks =c(0, .75, 1.25, 1.75, 2.25, 2.75, 4)

loc_error$bin <-cut(loc_error$deg_nn_dist, breaks = breaks)
# loc_error$bin <-cut_number(loc_error$deg_nn_dist, 6)


loc_error <- loc_error %>%
  filter(!is.na(bin))

loc_error %>%
  group_by(bin) %>%
  summarise(n = n())

loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
            x = mean(nn_dist_mean)) %>%
  ungroup() %>%
  ggplot(aes(x = x, y = le_mu)) + 
  geom_point(color = "#5aa67b",) + 
  geom_line(color = "#5aa67b",) +
  geom_errorbar(aes(ymin = le_mu - le_se,
                    ymax = le_mu + le_se),
                color = "#5aa67b",
                 ) + 
  xlab("Nearest Distractor") + 
  ylab("Localization error") +
  theme(aspect.ratio = 1.75)


loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
          x = mean(nn_dist_mean)) %>%
  with(lm(le_mu ~ x)) %>%
  summary()

loc_error %>%
  ggplot(aes(x = nn_dist_mean, y = loc_error_mean)) + 
  geom_point()

```

```{r}


loc_error$bin <- cut_interval(loc_error$cycles_mean, n = 6)

loc_error <- loc_error %>%
  filter(!is.na(bin))

loc_error %>%
  group_by(bin) %>%
  summarise(n = n())

loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
            x = mean(cycles_mean)) %>%
  ggplot(aes(x = x, y = le_mu)) + 
  geom_point(color = "#7a59a5",) + 
  geom_line(color = "#7a59a5",) + 
  geom_errorbar(aes(ymin = le_mu - le_se,
                    ymax = le_mu + le_se),
                color = "#7a59a5",) + 
  xlab("Cycles") + 
  ylab("Localization error") + 
  theme(aspect.ratio = 1.75)

loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
            x = mean(cycles_mean)) %>%
  with(lm(le_mu ~ x)) %>%
  summary()

loc_error %>%
  ggplot(aes(x = cycles_mean, y = loc_error_mean)) + 
  geom_point()


```


```{r}


loc_error$bin <- cut_interval(loc_error$sensitivity_mean, n = 6)

loc_error <- loc_error %>%
  filter(!is.na(bin))

loc_error %>%
  group_by(bin) %>%
  summarise(n = n())

loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
            x = mean(sensitivity_mean)) %>%
  ggplot(aes(x = x, y = le_mu)) + 
  geom_point(color = "#7a59a5",) + 
  geom_line(color = "#7a59a5",) + 
  geom_errorbar(aes(ymin = le_mu - le_se,
                    ymax = le_mu + le_se),
                color = "#7a59a5",) + 
  xlab("Goal-relevance") + 
  ylab("Localization error") + 
  theme(aspect.ratio = 1.75)

loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
            x = mean(sensitivity_mean)) %>%
  with(lm(le_mu ~ x)) %>%
  summary()

loc_error %>%
  ggplot(aes(x = sensitivity_mean, y = deg_loc_error)) + 
  geom_point()


```




## Localization Error - Fixed Resources


```{r echo=FALSE, results='hide'}

exp_data <- read_csv("../data/exp3/exp3_localization_error_fixed_resources_att.csv") %>%
filter(frame > 24)

dnd_data <- read_csv("../data/exp3/exp3_localization_error_fixed_resources_dnd.csv") %>%
  select(-contains("pred"))

model_perf <- read_csv("../data/exp3/exp3_localization_error_fixed_resources_perf.csv")

mean(model_perf$td_acc)

acc_thresh = 0.99
loc_error_thresh = 3.0
ecc_thresh = 0.99
exp_data <- exp_data %>%
  left_join(model_perf, by = c("chain", "scene", "tracker")) %>%
  # filter(td_acc > acc_thresh) %>%
  left_join(dnd_data, by = c("chain", "scene", "frame", "tracker")) %>%
  group_by(scene, frame, tracker) %>%
  summarise(across(c(cycles, pred_x, pred_y, loc_error, nn_dist, td_acc),
                   list(mean = mean)),
            )%>%
  ungroup() %>%
  # remove inaccurate trackers
  filter(td_acc_mean > acc_thresh) %>%
  # remove extreme loc error
  mutate(z_loc_error = scale(loc_error_mean)) %>%
  filter(z_loc_error < loc_error_thresh) %>%
  mutate(deg_loc_error = (loc_error_mean / 800) * 6.97,
         deg_nn_dist = (nn_dist_mean / 800) * 6.97,
         ecc = sqrt(pred_x_mean^2 + pred_y_mean^2) / 400) %>%
  # ignore eccentric objects
  filter(ecc < ecc_thresh)

```


```{r}

loc_error <- exp_data %>%
  select(scene, frame, tracker, nn_dist_mean, deg_nn_dist, deg_loc_error, 
         loc_error_mean, cycles_mean)

loc_error %>%
  ggplot(aes(x = deg_nn_dist)) + 
  geom_histogram(bins=30)

loc_error %>%
  ggplot(aes(x = deg_loc_error)) + 
  geom_histogram(bins=100)


```

```{r}

# bins from panel B (visually estimated)
panel_bins = c(1.0, 1.4, 1.7, 2.1, 2.6, 3.6)
# breaks = c(.32, 1.2, 1.55, 1.9, 2.35, 3.1, 4.0)
breaks = c(.8, 1.2, 1.55, 1.9, 2.35, 3.1, 4.0)
# breaks =c(0, .75, 1.25, 1.75, 2.25, 2.75, 4)

loc_error$bin <-cut(loc_error$deg_nn_dist, breaks = breaks)
# loc_error$bin <-cut_number(loc_error$deg_nn_dist, 6)


loc_error <- loc_error %>%
  filter(!is.na(bin))

loc_error %>%
  group_by(bin) %>%
  summarise(n = n())

loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
            x = mean(nn_dist_mean)) %>%
  ungroup() %>%
  ggplot(aes(x = x, y = le_mu)) + 
  geom_point() + 
  geom_line() +
  geom_errorbar(aes(ymin = le_mu - le_se,
                    ymax = le_mu + le_se),
                 ) + 
  xlab("Nearest Distractor") + 
  ylab("Localization error") +
  theme(aspect.ratio = 1.75)


loc_error %>%
  group_by(bin) %>%
  summarise(le_mu = mean(loc_error_mean),
            le_se = sd(loc_error_mean) / sqrt(n()),
          x = mean(nn_dist_mean)) %>%
  with(lm(le_mu ~ x)) %>%
  summary()

loc_error %>%
  ggplot(aes(x = nn_dist_mean, y = loc_error_mean)) + 
  geom_point()


```